from enum import Enum

class RegressionTestStrategy(Enum):
    ALL_AGGREGATES_NO_REWRITING = 1
    REWRITING_TIGHT = 2
    REWRITING_SHARED_CYCLE = 3
    REWRITING_LEVEL_MAPPINGS_AAAI = 4
    REWRITING_LEVEL_MAPPINGS = 5
    FULLY_GROUNDED_TIGHT = 6
    FULLY_GROUNDED_SHARED_CYCLE = 7
    FULLY_GROUNDED_LEVEL_MAPPINGS_AAAI = 8
    FULLY_GROUNDED_LEVEL_MAPPINGS = 9

